### ISSUE TITLE
Remote connections don't work

### ISSUE THREAD

**Issue by Banbury** [djungelorm/krpc#81] opened 2014-09-14 07:50 UTC
I'm trying to write a Java client for KRPC. Currently I can connect to the server locally. My client is recognized by the server. But when I try the same code on a remote computer, I get a 'connection reset' error.
* I changed the server IP to 0.0.0.0. This allowed my client to connect, but the sent data got lost.
* I turned off the firewall. Still no reaction.
* I tried to telnet the server, but the connection was immediately closed.
* tcpdump shows that the connection is established and the server sends an answer.

**Comment by djungelorm** [comment] 2015-03-04 14:47
I've got time to work on this stuff again - hoorah :) Are you still having issues with this?

@spigot: I've improved the python client code to remove that FIXME, so the client shouldn't try to decode an incomplete message 198ba74

**Comment by Banbury** [comment] 2015-03-06 15:14
I haven't tried it again. But I assume the problem didn't go away magically :).

**Comment by djungelorm** [comment] 2015-03-07 13:07
Do you have the code for the Java client so I can test it out?

I've done some Windows/Linux testing with the latest version of the python client and it works fine. I ran the server on Windows and the client on Linux, communicating over my wireless network. All the unit tests pass, and the example script works fine too.

I added a unit test that sends various combinations of CRLF characters over the wire as well, which passes (8c7e81c). Line endings shouldn't cause any issues, as the messages are treated as byte strings/byte arrays in python/C#. The issues @spigot linked on stackoverflow were caused by reading from files in text mode.

The "truncated string" error that @spigot noted should be fixed. This was caused by my horrendously naive use of socket.recv that led to the client attempting to decode messages before it had received all the data. I now have a much more robust bit of code to do the communication from the python side: https://github.com/djungelorm/krpc/blob/master/python/krpc/connection.py

**Comment by djungelorm** [comment] 2015-03-07 13:12
I should also point out, the connection protocol has changed somewhat since 0.1.3 was released.

I've updated the wiki accordingly: https://github.com/djungelorm/krpc/wiki/RPC-Protocol

**Comment by Loran425** [comment] 2015-03-10 00:39
Remote Connection works on local network in python.

**Closed** 2015-05-09 10:56 UTC
Labels: bug, python-client, server-api

**Comment by aefreedman** [comment] 2017-07-25 14:14
I'm getting something similar to this when trying to use a Raspberry Pi running Raspbian (Debian) to connect to a Windows Client. I get this error when running the Hello World example:

```
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "/home/pi/kpi/examples/hello-world.py", line 2, in <module>
    conn = krpc.connect(name='Hello World', address='192.168.1.125', rpc_port=50000, stream_port=50001)
  File "/usr/local/lib/python2.7/dist-packages/krpc/__init__.py", line 35, in connect
    ok_message = stream_connection.receive(Decoder.OK_LENGTH)
  File "/usr/local/lib/python2.7/dist-packages/krpc/connection.py", line 57, in receive
    raise socket.error("Connection closed")
error: Connection closed
```

I'll also sometimes get a `Connection reset by peer`. I've confirmed that this code works when trying Windows->Windows and OS X->Windows. The client does sometimes appear in the connections list in KSP.

**Comment by djungelorm** [comment] 2017-07-30 16:06
Looks like the server is closing the connection for some reason.

Could you try setting logLevel to "Debug" in ``GameData/kRPC/PluginData/settings.cfg``, then running the example again, and post the contents of ``KSP_x64_Data/output_log.txt`` on here so I can take a look.

**Comment by aefreedman** [comment] 2017-07-31 13:38
https://gist.github.com/aefreedman/0dea336140482fd4e08582fbd2fe259d

error is also sometimes tracing back to `connection.py` line 55 from `__init__.py` line 27

**Comment by starfleetorg** [comment] 2019-04-18 10:15
Try this:
connection = krpc.connect(address="WTF") #Replcae "WTF" with your server IP
